name: CI - Pylint Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    pylint-check:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.11"

            - name: Install Pylint
              run: |
                  python -m pip install --upgrade pip
                  pip install pylint
                  pip install -r requirements.txt

            - name: Run Pylint Check
              run: |
                  # Run Pylint only on files in the 'api' folder
                  pylint --fail-under=10 api/
