name: CI - Pylint Check  # Name of the workflow

on:
    push:  # Runs the workflow on every push to the main branch
        branches:
            - main
    pull_request:  # Also runs on every pull request targeting main
        branches:
            - main

jobs:
    pylint-check:
        runs-on: ubuntu-latest  # Runs the workflow on the latest Ubuntu OS

        steps:
            - name: Check out the repository
              uses: actions/checkout@v2  # Clones the repository into the runner

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.11"  # Ensures Python 3.11 is used

            - name: Install Pylint
              run: |
                  python -m pip install --upgrade pip
                  pip install pylint
                  pip install -r requirements.txt  # Install dependencies

            - name: Run Pylint Check
              run: |
                  # Run Pylint on all Python files EXCEPT those in the 'scripts/' folder
                  pylint --fail-under=10 $(git ls-files '*.py' ':!:scripts/*') && \

                  # Run Pylint on files inside 'scripts/' but IGNORE error E1120 (no-value-for-parameter)
                  pylint --fail-under=10 --disable=E1120 $(git ls-files 'scripts/*.py')
