name: CI - Code Formatting Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    black-format-check:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.11"

            - name: Install Black
              run: |
                  python -m pip install --upgrade pip
                  pip install black

            - name: Run Black Check
              run: |
                  black --check .
